### ISSUE TITLE
Support for Python 3.9

### ISSUE THREAD

**Issue by UweSauter** [DMTF/python-redfish-library#103]
Python 3.9 was released 2020-10-05.

**Comment by mraineri** [comment]
What specifically needs to be done for Python3.9 that goes beyond the current Python3 support?

**Comment by UweSauter** [comment]
I think that py39 should be added to tox.ini's

```
[tox]
envlist = py27,py34,py35,py36,py37,py38
```

Beyond that I don't know.

**Comment by mraineri** [comment]
Great, I see that now; thanks for clarifying!
