### ISSUE TITLE
So trying to use the example and I keep getting time outs.

### ISSUE THREAD

**Issue by tdwitham** [DMTF/python-redfish-library#113]
So I get a timeout response - can go to the browser and it all works fine,  any hints?

`import sys
import redfish

login_host = "https://10.250.2.2"
login_account = "root"
login_password = "tester"

sys.stdout.write("Before OBJ host=%s account=%s password=%s\n" % (login_host, login_account, login_password))
REDFISH_OBJ = redfish.redfish_client(base_url=login_host, username=login_account, password=login_password, \
                                     timeout=5, max_retry=3, default_prefix='/redfish/v1/Systems')
sys.stdout.write("After OBJ\n")

REDFISH_OBJ.login(auth="session")

response = REDFISH_OBJ.get("/redfish/v1/Systems", None)

sys.stdout.write("%s\n" % response)

REDFISH_OBJ.logout()
`

**Comment by tdwitham** [comment]
Ahh, it is becoming clearer now.  The proxy is working for the browser (Use
system proxy settings) but not functioning for this access.

Wookie

***@***.*** Source]$ curl -k -u root:tester -D - "https://
https://10.250.2.2/redfish/v1/"
HTTP/1.1 503 Service Unavailable
Server: squid/4.12
Mime-Version: 1.0
Date: Wed, 11 Aug 2021 14:39:11 GMT
Content-Type: text/html;charset=utf-8
Content-Length: 255
X-iboss-Error: ERR_DNS_FAIL 0

curl: (56) Received HTTP code 503 from proxy after CONNECT





Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
Are your proxy settings configured via the following environment variables like this, or is there something else your browser is using?

```
export HTTP_PROXY="http://192.168.1.10:8888"
export HTTPS_PROXY="http://192.168.1.10:8888"
```

**Comment by tdwitham** [comment]
Yes,  in .bashrc, /etc/profile and /etc/profile.  Looking to see if there
is anything strange.

Wookie

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by tdwitham** [comment]
Okay I disabled the proxy for the 10.250.0.0/16 network and got to a
connection.

And it seems like I need an SSL certificate for each and every one of the
servers?  Is this correct?

Wookie

curl -k -u root:tester -D - "https://10.250.2.2/redfish/v1/Systems"
HTTP/1.1 401 Unauthorized
WWW-Authenticate: Basic realm="Redfish"
Content-Type: application/json
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-UA-Compatible: IE=11
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Cache-Control: no-store, no-cache
Pragma: no-cache
Content-Security-Policy: default-src 'none'; script-src 'self'; style-src
'self'; frame-src 'self'; font-src 'self'; connect-src 'self'; img-src
'self'
Content-Length: 792
Date: Wed, 11 Aug 2021 20:22:29 GMT

{"error":{"code":"Base.1.5.0.GeneralError","message":"A general error has
occurred. See ExtendedInfo for more
***@***.******@***.***":"#Message.v1_0_7.Message","MessageId":"Base.1.5.0.NoValidSession","Message":"There
is no valid session established with the
implementation.","Severity":"Critical","Resolution":"Establish a session
before attempting any
***@***.***":"#Message.v1_0_7.Message","MessageId":"Base.1.5.0.ResourceAtUriUnauthorized","Message":"While
accessing the resource at /redfish/v1/Systems, the service received an
authorization error
failed.","MessageArgs":["/redfish/v1/Systems","failed"],"Severity":"Critical","Resolution":"Ensure
that the appropriate access is provided for the service in order for it to
access the URI."}]}}

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
No, installing a certificate isn't needed for the interface to work (but it is encouraged since most services come with a self-signed certificate by default).

At least from the messages in your latest response, that would indicate to me the credentials "root" and "tester" are not valid. Were those same credentials working in the browser when you tried accessing Redfish resources via that path?

**Comment by tdwitham** [comment]
Yes, that along with fixing some DPCP issues resolved the problem.

Thanks,  but is there an example that actually parses the json?  I've been
looking and
haven't found it.

Wookie

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
The library itself doesn't contain that level of logic; it stops at producing a Python dictionary from the the JSON response, and leaves it up to the caller to extract the dictionary values that are relevant to their usage.

We do have a separate set of scripts that consumes this library and does more of the higher order types of operations (like collecting and displaying log data), and could be used as a sample for how to walk a Redfish service to find the data of interest. That project can be found here: https://github.com/DMTF/Redfish-Tacklebox

**Comment by tdwitham** [comment]
Okay so I'm trying to use rf_system_inventory.py and I keep getting an
error.

python3 ft_system_inventory.py --user test --password tester --rhost
10.250.2.2

And I get the following error message.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
885, in _rest_request
    self._conn.request(method.upper(), reqpath, body=body,
AttributeError: 'NoneType' object has no attribute 'request'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rf_sys_inventory.py", line 32, in <module>
    redfish_obj = redfish.redfish_client( base_url = args.rhost, username =
args.user, password = args.password )
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
1161, in redfish_client
    max_retry=max_retry)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
1074, in __init__
    max_retry=max_retry)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
452, in __init__
    self.get_root_object()
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
636, in get_root_object
    raise excp
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
634, in get_root_object
    resp = self.get('%s%s' % (self.__url.path, self.default_prefix))
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
669, in get
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
1111, in _rest_request
    skip_redirect=skip_redirect)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
967, in _rest_request
    raise RetriesExhaustedError() from cause_exception
redfish.rest.v1.RetriesExhaustedError

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
You need to specify the schema with the address; instead of `--rhost 10.250.2.2` it should be `--rhost http://10.250.2.2`

**Comment by tdwitham** [comment]
Ahh,  okay then - but now:

 python3 rf_sys_inventory.py --user test --password tester --rhost
https://10.250.2.2
returning true (re)
returning true (re)
Traceback (most recent call last):
  File "rf_sys_inventory.py", line 37, in <module>
    inventory = redfish_utilities.get_system_inventory( redfish_obj )
  File
"/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py",
line 60, in get_system_inventory
    catalog_systems( context, chassis.dict["Links"], "ComputerSystems",
chassis_instance )
  File
"/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py",
line 118, in catalog_systems
    catalog_storage( context, system_res.dict, "Storage", inventory )
  File
"/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py",
line 157, in catalog_storage
    catalog_array( context, member_res.dict, "Drives", inventory["Drives"] )
  File
"/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py",
line 79, in catalog_array
    catalog_resource( member_res.dict, inventory )
  File
"/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py",
line 175, in catalog_resource
    if item["Uri"] == ***@***.***"]:
KeyError: ***@***.***'
Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
It's hard to tell without the payload in question, but it appears the service is not rendering the mandatory `@odata.id` property in one or more of its Drive resources. If this is the case, we might need to consider adding some workaround flags to bypass services that are not implementing mandatory properties to Tacklebox.

**Comment by mraineri** [comment]
It could be that there was an error in getting the resource in question (and error payloads do not have `@odata.id` properties). This might be a good time for me to revisit this tool and improve the error handling.

**Comment by tdwitham** [comment]
Is there someway I can dump the payload out for you?  And I will track down
John L.  and see what he
has to say.

Wookie

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
You should be able to get it from a browser and paste it here. From the trace, it's following the links through Systems, Storage, and Drives.

Depending on the number of storage subsystems, it might get difficult to track down the exact culprit. I would start with trying to find the first drive reported in the first storage subsystem.
* Go to /redfish/v1/Systems
* Go to the first system instance in the Members array
* Go to the Storage collection found in the first system (look for the "Storage" property)
* Go to the first storage instance in the Members array
* Go to the first drive listed in the "Drives" property

I'm hoping the payload found at that last step will tell us what's going on, but if it's not clear, I can make a debug branch in Tacklebox for tracing what's going on.

**Comment by tdwitham** [comment]
Well actually it was the last drive.

*For https://10.250.2.2/redfish/v1/Systems/............/Storage/1/
<https://10.250.2.2/redfish/v1/Systems/............/Storage/1/>*


@odata.context "/redfish/v1/$metadata#Storage.Storage"
@odata.id "/redfish/v1/Systems/............/Storage/1"
@odata.type "#Storage.v1_7_0.Storage"
Id "1"
Name "Local Storage Controller"
Drives
0
@odata.id "/redfish/v1/Systems/............/Storage/1/Drives/0"
1
@odata.id "/redfish/v1/Systems/............/Storage/1/Drives/1"
2
@odata.id "/redfish/v1/Systems/............/Storage/1/Drives/2"
Links
Enclosures
0
@odata.id "/redfish/v1/Chassis/RackMount"
@odata.etag "f289c576d773b62853a878a14f823232"

*For https://10.250.2.2/redfish/v1/Systems/............/Storage/1/Drives/2
<https://10.250.2.2/redfish/v1/Systems/............/Storage/1/Drives/2>*


error
code "Base.1.5.0.GeneralError"
message "A general error has occurred. See ExtendedInfo for more
information."
@Message.ExtendedInfo
0
@odata.type "#Message.v1_0_7.Message"
MessageId "Base.1.5.0.ResourceMissingAtURI"
Message "The resource at the URI
/redfish/v1/Systems/............/Storage/1/Drives/2 was not found."
MessageArgs
0 "/redfish/v1/Systems/............/Storage/1/Drives/2"
Severity "Critical"
Resolution "Place a valid resource at the URI or correct the URI and
resubmit the request."


Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
So, it is the latter case; the Storage resource is presenting links to Drives that result in a 404. I can certainly add better error handling to not crash in these cases, but it would be good to understand why the service you're working with isn't accepting the Drive URIs its presenting. It could be a case where the drive itself is absent, but we have modeling guidance in Redfish to render the resource with the "State" property inside of "Status" as "Absent" rather than returning a 404.

**Comment by jcleung5549** [comment]
What do you get when you issue a GET /redfish/v1/Systems/............/Storage/1/Drives/0 via Postman? Anything you do via the library, you can debug by walking the resource tree manually.

**Comment by tdwitham** [comment]
About what I expect.


@odata.context "/redfish/v1/$metadata#Drive.Drive"
@odata.id "/redfish/v1/Systems/............/Storage/1/Drives/0"
@odata.type "#Drive.v1_6_0.Drive"
Id "0"
Name "PCIe S0 B3 D0 F0"
Protocol "PCIe"
MediaType "SSD"
CapacityBytes 499122176
RotationSpeedRPM 0
Model "INTEL SSDPEKKA512G7 "
SerialNumber "BTPY719309J6512F "
Revision "PSF119D"
Oem
Storage
@odata.type "#OEMExtensions.Storage"
PciClass 1
VendorId "0x8086"
DeviceId "0xF1A5"
SubVendorId "0x8086"
SubDeviceId "0x390A"
@odata.etag "b2c6540abecd52b008dca4bd69335e36"

Wookie

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
@tdwitham I just released some changes that might help; rf_sys_inventory has a "workaround" flag added to bypass that issue you hit.

**Comment by tdwitham** [comment]
Thanks, I'll check it out.

Wookie

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
In this case it looks like you can't even log into the system; it's trying to access /redfish/v1/ but getting a 400. Can you access the resource in the browser?

**Comment by tdwitham** [comment]
Yes,  yes I can.  Let me look into it.

Wookie

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by tdwitham** [comment]
And yes it works with the user/password I'm giving it. :-(

Wookie
Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
I just noticed the URI given is not correct. You're missing a `/` in the rhost argument: `http:/10.250.2.2`.

**Comment by tdwitham** [comment]
Okay,  so now a 404 error.  But I found it with the browser.
***@***.*** scripts]$ rf_sys_inventory.py --user test --password
tester --rhost http://10.250.2.2/v1/Systems
returning true (re)
returning true (re)
Traceback (most recent call last):
  File "/usr/local/bin/rf_sys_inventory.py", line 32, in <module>
    redfish_obj = redfish.redfish_client( base_url = args.rhost, username =
args.user, password = args.password )
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
1161, in redfish_client
    max_retry=max_retry)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
1074, in __init__
    max_retry=max_retry)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
452, in __init__
    self.get_root_object()
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
640, in get_root_object
    "return code: %d" % resp.status)
redfish.rest.v1.ServerDownOrUnreachableError: Server not reachable, return
code: 404


Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
For --rhost, you would leave off the resource URI (it's just the schema + IP address). So, it should be `--rhost https://10.250.2.2`.

**Comment by tdwitham** [comment]
***@***.*** scripts]$ rf_sys_inventory.py --user test --password
tester --rhost http://10.250.2.2
returning true (re)
returning true (re)
returning true (re)
Traceback (most recent call last):
  File "/usr/local/bin/rf_sys_inventory.py", line 33, in <module>
    redfish_obj.login( auth = "session" )
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
1017, in login
    raise InvalidCredentialsError(delay)
redfish.rest.v1.InvalidCredentialsError: 0

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
Would it be possible to try https instead of http? Services tend to reject Redfish Session Login when using http since it's not a secure communication channel.

`rf_sys_inventory.py --user test --password tester --rhost https://10.250.2.2`

**Comment by tdwitham** [comment]
Darn I thought I had entered https,  but still an error.

***@***.*** scripts]$
***@***.*** scripts]$ rf_sys_inventory.py --user test --password
tester --rhost https://10.250.2.2
returning true (re)
returning true (re)
Traceback (most recent call last):
  File "/usr/local/bin/rf_sys_inventory.py", line 37, in <module>
    inventory = redfish_utilities.get_system_inventory( redfish_obj )
  File
"/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py",
line 60, in get_system_inventory
    catalog_systems( context, chassis.dict["Links"], "ComputerSystems",
chassis_instance )
  File
"/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py",
line 118, in catalog_systems
    catalog_storage( context, system_res.dict, "Storage", inventory )
  File
"/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py",
line 157, in catalog_storage
    catalog_array( context, member_res.dict, "Drives", inventory["Drives"] )
  File
"/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py",
line 79, in catalog_array
    catalog_resource( member_res.dict, inventory )
  File
"/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py",
line 175, in catalog_resource
    if item["Uri"] == ***@***.***"]:
KeyError: ***@***.***'


Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
Okay, can you add the new `--workaround` argument to attempt to bypass service-side issues?

**Comment by mraineri** [comment]
It also doesn't seem like you've pulled down the latest updates to Tacklebox; the line reported in the exception trace doesn't match the updates we've pushed last week and it correlates with the older version prior to the introduction of the `--workaround` flag for the script.

**Comment by tdwitham** [comment]
Dang,  in the wrong environment.  Fixed it and now it just hangs.  Here is
the ctl-c out of the script.

***@***.***# python3 ./scripts/rf_sys_inventory.py -u test -p tester -r
https://10.250.2.2 --workaround
^CTraceback (most recent call last):
  File "./scripts/rf_sys_inventory.py", line 31, in <module>
    redfish_obj = redfish.redfish_client( base_url = args.rhost, username =
args.user, password = args.password )
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
1165, in redfish_client
    max_retry=max_retry)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
1075, in __init__
    max_retry=max_retry)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
453, in __init__
    self.get_root_object()
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
635, in get_root_object
    resp = self.get('%s%s' % (self.__url.path, self.default_prefix))
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
670, in get
    headers=headers)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
1112, in _rest_request
    skip_redirect=skip_redirect)
  File "/usr/local/lib/python3.6/site-packages/redfish/rest/v1.py", line
887, in _rest_request
    headers=headers)
  File "/usr/lib64/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib64/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/lib64/python3.6/http/client.py", line 950, in connect
    self._tunnel()
  File "/usr/lib64/python3.6/http/client.py", line 924, in _tunnel
    (version, code, message) = response._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib64/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt


Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
How long did you wait? Depending on the size of the service, it may take a minute for the inventory to be collected.

**Comment by tdwitham** [comment]
Ahh,  yes 38 seconds but it works.

Thanks,
Do you want to see the errors that it produced?

Wookie
Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
Sure, that would be good to see for me to compare with what I'm currently expecting. It might need to be provided back to the service vendor.

**Comment by tdwitham** [comment]
***@***.*** redfishtoollib]$ rf_sys_inventory.py --user test
--password tester --rhost https://10.250.2.2 --workaround --details
returning true (re)
returning true (re)
/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py:100:
UserWarning: Could not access
'/redfish/v1/Systems/............/Storage/1/Drives/2'.  Contact your
vendor.  Skipping...
  warnings.warn( "Could not access '{}'.  Contact your vendor.
Skipping...".format( ***@***.***"] ) )
/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py:72:
UserWarning: Could not access '/redfish/v1/Chassis/Baseboard'.  Contact
your vendor.  Skipping...
  warnings.warn( "Could not access '{}'.  Contact your vendor.
Skipping...".format( chassis_uri ) )
/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py:72:
UserWarning: Could not access '/redfish/v1/Chassis/AICRiser1Slot1'.
Contact your vendor.  Skipping...
  warnings.warn( "Could not access '{}'.  Contact your vendor.
Skipping...".format( chassis_uri ) )
/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py:72:
UserWarning: Could not access '/redfish/v1/Chassis/FrontPanel'.  Contact
your vendor.  Skipping...
  warnings.warn( "Could not access '{}'.  Contact your vendor.
Skipping...".format( chassis_uri ) )
/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py:72:
UserWarning: Could not access '/redfish/v1/Chassis/HSBackplane4'.  Contact
your vendor.  Skipping...
  warnings.warn( "Could not access '{}'.  Contact your vendor.
Skipping...".format( chassis_uri ) )
/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py:72:
UserWarning: Could not access '/redfish/v1/Chassis/PCIeRiser1'.  Contact
your vendor.  Skipping...
  warnings.warn( "Could not access '{}'.  Contact your vendor.
Skipping...".format( chassis_uri ) )
/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py:72:
UserWarning: Could not access '/redfish/v1/Chassis/PCIeRiser2'.  Contact
your vendor.  Skipping...
  warnings.warn( "Could not access '{}'.  Contact your vendor.
Skipping...".format( chassis_uri ) )
/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py:72:
UserWarning: Could not access '/redfish/v1/Chassis/PCIeRiser3'.  Contact
your vendor.  Skipping...
  warnings.warn( "Could not access '{}'.  Contact your vendor.
Skipping...".format( chassis_uri ) )
/usr/local/lib/python3.6/site-packages/redfish_utilities/inventory.py:72:
UserWarning: Could not access '/redfish/v1/Chassis/PwrSupply1FRU'.  Contact
your vendor.  Skipping...
  warnings.warn( "Could not access '{}'.  Contact your vendor.
Skipping...".format( chassis_uri ) )

And then it is sort of what is expected.

Wookie

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
What happens when you try to access URIs like "/redfish/v1/Chassis/PCIeRiser3" in your browser?

**Comment by tdwitham** [comment]
Works ok for me,  I was going to ask you about that. :-)


Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
What do you get back as a response in your browser?

I may need to add more info info to the warning messages to show what exactly went wrong.

**Comment by tdwitham** [comment]
Didn't it come as an attachment?  I included it.

Wookie

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
I don't think email attachments come through on the GitHub issue; only the text gets posted as far as I know.

**Comment by tdwitham** [comment]
Trying again.

Wookie

Timothy D. Witham - 1815 SW Pheasant Dr - Aloha, OR 97003 -
Cell (503)-702-2871 - Office 503-207-6556 x101 - Fax (503) 928-6447
www.forestmoondevelopment.com -

**Comment by mraineri** [comment]
Closing; the issues here are related to non-conformant URIs from the service. Tacklebox has an enhancement opened to allow for a user to control whether the tools dynamically adjust to non-conformant URIs or make 1.6.0 assumptions about URIs (https://github.com/DMTF/Redfish-Tacklebox/issues/75), which is the remainder of the problem in this issue.
