### ISSUE TITLE
What is the default_prefix for?

### ISSUE THREAD

**Issue by nathanlin24** [DMTF/python-redfish-library#115]
Can someone please point me to documentation on _default_prefix_? I'm fairly new to the Redfish APIs not sure I understand what is it for. My code seems to work fine without setting the prefix. Thanks.

**Comment by mraineri** [comment]
The default_prefix really is just the service root path. On all conformant implementations, this would be `/redfish/v1`, and this value is used by default if you don't specify one. There may have been a need originally to control this for implementations that were under development and did not start their URIs at `/redfish/v1`, but beyond that type of usage I'm not aware of any need to set it.

It also is only used when the Redfish object is instantiated; when you first make the object and log in, it will go to the service root (specified by the default_prefix value), and then find the session collection to log into the service. All other requests after this point do not use default_prefix.

We can certainly clarify the documentation to help with how it's used.
