### ISSUE TITLE
Unix socket support

### ISSUE THREAD

**Issue by JordanCHW** [DMTF/python-redfish-library#120]
Any chance to implement unix socket support? Thanks!

**Comment by mraineri** [comment]
It looks like with the recent changes to use `requests`, we can further build on that to leverage `requests-unixsocket` for that sort of functionality.

It seems like you can do something like this:

```
# Access /redfish/v1 from /tmp/redfish.sock
session = requests_unixsocket.Session()
r = session.get('http+unix://%2Ftmp%2Fredfish.sock/path/to/page')
```

Is this the type of thing you're looking for? Essentially from a tooling perspective you'd be able to pass in `http+unix://<percent-encoded-socket-filepath>` as the service address.

**Comment by JordanCHW** [comment]
Yes, that's exactly what I'm looking for. Because the Redfish validators depend on this library to create the Redfish client, it would be great if this library support it.

**Comment by mraineri** [comment]
Would you be able to test the branch "unix-sockets"? I don't have any systems to verify things for myself.

**Comment by JordanCHW** [comment]
Sure, I just tried that, it works. That's awesome, thanks!
