### ISSUE TITLE
Returned data type from Assembly.bin changed in versioning 3.1.0

### ISSUE THREAD

**Issue by ldonova1992** [DMTF/python-redfish-library#125]
In version 3.1.0, the data type returned when performing a GET on an Assembly.bin changed from bytes to str. I'm not sure if that is intentional and correct for it be of type str now instead of bytes since its .bin and the content-type is application/octet-stream. Is this valid?

in version 3.0.3
![image](https://user-images.githubusercontent.com/45437442/166263034-a817b701-997a-4e41-a282-d062cf70cb75.png)

in version 3.1.0: 
![image](https://user-images.githubusercontent.com/45437442/166263090-ebe72ae6-914f-4c83-a973-46e6b996b9c8.png)

**Comment by mraineri** [comment]
This seems like an inadvertent change when migrating to the `requests` module. Will need to look at this further.
