### ISSUE TITLE
Timeout in HTTP Method

### ISSUE THREAD

**Issue by sykim1009** [DMTF/python-redfish-library#136]
Hello!
Do you have any plan to add timeout element in HTTP Method(GET,POST,UPDATE...)?
I really hope that Time out in method will be available!!
Thank you!

```
response = REDFISH_OBJ.get("/redfish/v1/systems/1", None)

response = REDFISH_OBJ.post("/redfish/v1/systems/1/Actions/ComputerSystem.Reset", body=body)
```

```
response = REDFISH_OBJ.get("/redfish/v1/systems/1", timeout=3)

response = REDFISH_OBJ.post("/redfish/v1/systems/1/Actions/ComputerSystem.Reset", body=body, timeout=3)
```

**Comment by mraineri** [comment]
We haven't had a request for one until this point (it seemed the one you can set when creating the Redfish object has been sufficient for people). We can certainly add one for specific requests like this.

**Comment by sykim1009** [comment]
Thank you for your review!!
Based on your comments, I understand that it is possible to add one.
I hope that it will be available on next version.
Thank you!!

**Comment by PeterKchen2** [comment]
Dear mraineri

add timeout element in HTTP Method(GET, POST, UPDATE...) is useful when needing post large data (this case needs a specific timeout, maybe 20 to 30 seconds, and do not want to let all requests wait timeout 20 to 30 seconds)
