### ISSUE TITLE
Does the library work also with Simulator/Emulator/Mockyup Server?

### ISSUE THREAD

**Issue by lollypop96** [DMTF/python-redfish-library#137]
Hi, sorry to disturb! I am pretty new to redfish, dmtf, etc. and I wanted to ask you if this library works also when using the simulator, the emulator or the mockup server (which can be found here: https://github.com/orgs/DMTF/repositories) or if its usage is limited to the official redfish api service and therefore I need to authenticate with the official credentials.

Thank you in advance and sorry if the question might look stupid.

**Comment by mraineri** [comment]
Yes it does work with various mockup tools. Keep in mind though, some functionality won't work with specific tools. For example, Redfish sessions aren't supported by the Redfish Mockup Server, so when you instantiate the library's Redfish object, you'll need to specify HTTP basic authentication.

**Comment by rahlvers** [comment]
The Swordfish API Emulator (https://github.com/SNIA/Swordfish-API-Emulator) is being enhanced to work against the service validator, interop validator and the protocol validator.

**Comment by mraineri** [comment]
@lollypop96 if this answers your question, do you mind if we close the issue? Is there anything else on this subject we can clarify for you?

**Comment by mraineri** [comment]
Closing; no further updates and the question was answered.
