### ISSUE TITLE
redfish.redfish_client insecure connection

### ISSUE THREAD

**Issue by ravixilinx** [DMTF/python-redfish-library#152]
Hi,

Is there any option with redfish_client to make insecure connection, similar to package "requests.request" with "verify=false" option?

Regards,
Ravi

**Comment by mraineri** [comment]
At this time this is entirely driven based on the usage of CA certificates when instantiating the Redfish object (it's not a simple boolean to toggle this off/on). The intent in the original implementation of this library is the `cafile` parameter contains the file path to the CA certificate to use for verification.

Although looking at the code here, I think this is a bug: https://github.com/DMTF/python-redfish-library/blob/main/src/redfish/rest/v1.py#L908

We should be passing "verify" down as a boolean and not the CA filepath string (if given). I'm surprised no one has hit this yet, but since the default behavior is to pass down false here, no one must be providing their own CA certificate.

**Comment by ravixilinx** [comment]
I was able to run a redfish get command using "requests.request" with insecure connection.

But using redfish module (redfish_client) leads an error "redfish.rest.v1.ServerDownOrUnreachableError: Server not reachable, return code: 401", hence asked the above query.
For this test, I had modified the example from this repo with IP and port number. Any help in this regard is much appreciated.

**Comment by mraineri** [comment]
With `requests`, are you using HTTP Basic Auth? For the example, can you try changing `REDFISH_OBJ.login(auth="session")` to `REDFISH_OBJ.login(auth="basic")`?

I'm wondering if there's an issue with the service and Redfish session login.

**Comment by mraineri** [comment]
Also looking at the usage of that exception, it would occur prior to any sort of authentication. The first thing the library does is discover the service by accessing /redfish/v1/ without any sort of credentials.

When you're using `requests`, are you able to access /redfish/v1/ without providing any authorization headers?

**Comment by ravixilinx** [comment]
Thanks for the response.

import requests
url = "https://<IP>:<port>/2/redfish/v1"
payload = {}
headers = {
  'Authorization': 'Basic <session key>'
}
# without 'verify=Flase' this code does not work
response = requests.request("GET", url, headers=headers, data=payload, verify=False)
print(response.text)


With redfish module that has issues is:

import sys
import redfish

login_host = "https://<IP>:<port>"

## Below line leads to error
REDFISH_OBJ = redfish.redfish_client(base_url=login_host, sessionkey='<session key>', default_prefix='/2/redfish/v1')
REDFISH_OBJ.login(auth="session")
response = REDFISH_OBJ.get("/redfish/v1/systems/1", None)
sys.stdout.write("%s\n" % response)
REDFISH_OBJ.logout()

**Comment by mraineri** [comment]
Can you try this (no authorization header)?

```
import requests
url = "https://<IP>:<port>/2/redfish/v1"
payload = {}
**# without 'verify=Flase' this code does not work**
response = requests.request("GET", url, data=payload, verify=False)
print(response.text)
```

**Comment by ravixilinx** [comment]
Without header, i get 'access denied' error as below:

  warnings.warn(
{
    "error": {
        "@Message.ExtendedInfo": [
            {
                "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
                "Oem": {
                    "Microsoft": {
                        "@odata.type": "#Ocs.v1_0_0.Message",
                        "CompletionCode": "Failure",
                        "Description": "Access denied"
                    }
                }
            }
        ]
    }
}

**Comment by mraineri** [comment]
So, that confirms my suspicion. It's not an issue with the "verify" flag, but rather the service you're using is non-conformant. "/redfish/v1/" is required by the specification to allow requests without authorization headers. The Redfish library needs to do upfront discovery of the service prior to logging in, and this behavior makes it impossible.

**Comment by mraineri** [comment]
@ravixilinx is there any way to reach out to the vendor for support on this? There is definitely a problem with the Redfish service and its handling of resources listed in the spec as not requiring authentication.

The other path to work around this would be to wrap the instantiation of the Redfish client object with try/except blocks, something like...

```
try:
    REDFISH_OBJ = redfish.redfish_client( <.... parameters> )
except ServerDownOrUnreachableError:
    pass
```

**Comment by ravixilinx** [comment]
At present I dont have any way to reach the vendor. I will let them know about this issue when I come accross.
With 'try, except' code, it goes through but REDFISH_OBJ does not get created.

**Comment by mraineri** [comment]
@ravixilinx we've been discussing this more internally and we're still hesitant to put a workaround in the official repository for this issue; adding such things can encourage other implementations to misbehave. We do think this really needs to be reported to the vendor so they can fix their software.

However, you should be able to fork the repository and apply a workaround for yourself so you can make forward progress. The patch file here should work around the issue you're having. Please let me know if you need help with applying this patch.

[Auth-Workaround.patch](https://github.com/DMTF/python-redfish-library/files/12972874/Auth-Workaround.patch)

**Comment by ravixilinx** [comment]
[AMD Official Use Only - General]

Hi Mike,

Please ignore this request for now.
We will get back if we don't find alternative.

Regards,
Ravi

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ravixilinx** [comment]
Kamtalwar, Ravi Shankar would like to recall the message, "[DMTF/python-redfish-library] redfish.redfish_client insecure connection (Issue #152)".

**Comment by mraineri** [comment]
Closing; issue is with a non-conformant service that needs to be fixed by the vendor.
