### ISSUE TITLE
Getting Fans infromation

### ISSUE THREAD

**Issue by acckiydarik** [DMTF/python-redfish-library#153]
Hello, i apologise, but who can help me to write code on python3 for printing Name and Status of  FAN?

output slice:
 'MemberId': '0', 'Name': 'FAN1', 'SensorNumber': 65, 'PhysicalContext': 'Fan', 'Status': {'State': 'Enabled', 'Health': 'OK'}

My code works incorrectly and I don't know how to fix it :(

`
REDFISH_OBJ = redfish.redfish_client(base_url=f"https://{server_ip}", username=login, password=password,
                                     default_prefix='/redfish/v1/')
try:

    REDFISH_OBJ.login(auth="session")

    def retrieve_and_print_info(component_name, component_url):
        response = REDFISH_OBJ.get(component_url)

        if response.status == 200:
            component_data = response.dict
            component_members = component_data.get("Fans", [])

            print(f"{component_name} Members:")
            for member in component_members:
                member_url = member.get("@odata.id")
                if member_url:
                    member_response = REDFISH_OBJ.get(member_url)
                    if member_response.status == 200:
                        member_data = member_response.dict
                        print(f"Fan Member Data:")
                        print(member_data)
        else:
            print(f"{response.status}")

    fan_uri = '/redfish/v1/Chassis/1/Thermal#/Fans/1' 
    retrieve_and_print_info("Fan", fan_uri)
finally:
    REDFISH_OBJ.logout()

`
    
[odata.context.txt](https://github.com/DMTF/python-redfish-library/files/13180097/odata.context.txt)

thank you.

**Comment by mraineri** [comment]
Keying off this statement:

`fan_uri = '/redfish/v1/Chassis/1/Thermal#/Fans/1'`

One thing to be aware of is when you see "#" in the URI, that full URI itself is not individually GETable; you can only perform HTTP operations on the portion to the left of the #; the portion to the right of the # contains a pointer into the payload.

So, you'd start from `/redfish/v1/Chassis/1/Thermal`, and iterate over the `Fans` property. So, for example...

```
REDFISH_OBJ.login(auth="session")

def retrieve_and_print_info(component_name, component_url):
    response = REDFISH_OBJ.get(component_url)

    if response.status == 200:
        component_data = response.dict
        component_members = component_data.get("Fans", [])

        print(f"{component_name} Members:")
        for member in component_members:
            member_data = member_response.dict
            print(f"Fan Member Data:")
            print(member_data)
    else:
        print(f"{response.status}")

thermal_uri = '/redfish/v1/Chassis/1/Thermal' 
retrieve_and_print_info("Fan", thermal_uri)
```

**Comment by acckiydarik** [comment]
Omg, got it, thank you so much )
