### ISSUE TITLE
`get_root_object` call in `RestClientBase` `__init__` method

### ISSUE THREAD

**Issue by jpavlav** [DMTF/python-redfish-library#163]
Hey folks!

We just started a project that is utilizing this library. We notice that there is a network call during instantiation of the object [here](https://github.com/DMTF/python-redfish-library/blob/7c7df89a70d5419d0fed4010b2d8e3668584b7be/src/redfish/rest/v1.py#L500). I want to propose that we make this network call optional, by introducing a keyword argument to the `__init__` method of the redfish client that is defaulted to `True` to preserve the current behavior. Here are a few reasons why:

* If the process that is utilizing this library doesn't know the BMC IP up front it prevents a client from being created.
* If for some reason the BMC IP never returns a response, instantiation _can_ be permanently stuck behind waiting for a response on the socket.
* It's more flexible overall, allows for new/different use-cases, and doesn't impede anyone who is expecting to get that for free.

I'll kick up a PR for this.

**Comment by mraineri** [comment]
I'm certainly open to it and can see the benefits you're pointing out. One thing to be cautious of is the call to `get_service_root` caches the service root info automatically on behalf of the caller. I'd like to ensure that we maintain that automatic caching. Perhaps we can add a second call to it as part of `login` if it wasn't cached previously?

**Comment by jpavlav** [comment]
@mraineri Kicked up a PR for this. Should be good to go for review 👍

**Comment by mraineri** [comment]
Closing; merged the PR for this request.
