### ISSUE TITLE
Change the format of rest response for v1.py

### ISSUE THREAD

**Issue by archerwen** [DMTF/python-redfish-library#167]
Hi DMTF,

I use this python library to develop a robot automation test framework.
From this part of "v1.py".
![image](https://github.com/user-attachments/assets/cf695899-3aed-450b-b724-ec7e73d66d80)

**Can someone change the response as a Json format?
I think this is useful if anyone try to analyze the report.**

Below is the coding example that I try to show as a json format to the report.
![image](https://github.com/user-attachments/assets/d14ba12d-ecdd-41ac-9aa8-f38ee9ccdb39)

![image](https://github.com/user-attachments/assets/979197b8-6681-493d-a964-0332116c8e35)

**Comment by mraineri** [comment]
I think that would be a useful change. Would you be willing to make a pull request with the changes?

**Comment by archerwen** [comment]
Sure, but let me try if any side effect first.

**Comment by mraineri** [comment]
Closing; PR merged
