### ISSUE TITLE
Two problems about using redfish==2.0.2

### ISSUE THREAD

**Issue by lxfpast** [DMTF/python-redfish-library#17]
For the following code(master/src/redfish/rest/v1.py), I met two problems when using redfish==2.0.2.
These two problems didn't existed in the previous version 2.0.0. 

line:(888-890)
"
if resp.status != 200:
                raise BadRequestError("Invalid session resource: %s, "\
                                   "return code: %d" % session_loc, resp.status)
"

1. First question:
On line 888 of the code, logout of session failure when status code is not equal to 200. What about status like 204?  Is it also a failure?
Based on HTTP protocol, 2xx all are treated as sucess. Hope normally status code like 202/204 can be treated as sccess.

2. Second question:
When I call logout() to logout of session, our status code is 204, expected exception is not raised, below Typeerror exception is displayed. 
 TypeError: not enough arguments for format string

I think there is an error in the 890 row of the modified code, One '%' can not format multiple strings.
When I change "return code: %d" % session_loc, resp.status) to "return code: %d" %(session_loc, resp.status)), Typeerror problem is resolved.

Please help to clarify it and fix it if they are really bugs.

**Comment by samerhaj** [comment]
I see the same issue
