### ISSUE TITLE
ssl certs verification is disabled in RestClient

### ISSUE THREAD

**Issue by hemanthnakkina** [DMTF/python-redfish-library#19]
SSL certificate verification is disabled.
https://github.com/DMTF/python-redfish-library/blob/master/src/redfish/rest/v1.py#L429

It will be good to parameterize the SSL certificate verification as part of constructor.
This will enable the consumers of the library to decide on enable/disable SSL certificate verification.

**Comment by mraineri** [comment]
Pull request approved
