### ISSUE TITLE
POST complaining about malformed JSON

### ISSUE THREAD

**Issue by gkeishin** [DMTF/python-redfish-library#25]
A simple code to do action on a given target. I'm not sure if there is problem in my example code there.. via request API can do correctly but with the redfish API, i seem to see this JSON malform error.

Resource meta data and target info snippet
```
{
  "@odata.context": "/redfish/v1/$metadata#ComputerSystem.ComputerSystem",
  "@odata.id": "/redfish/v1/Systems/1",
  "@odata.type": "#ComputerSystem.v1_3_0.ComputerSystem",
  "Actions": {
    "#ComputerSystem.Reset": {
      "ResetType@Redfish.AllowableValues": [
        "On",
        "ForceOff",
        "GracefulRestart",
        "GracefulShutdown"
      ],
      "target": "/redfish/v1/Systems/1/Actions/ComputerSystem.Reset"
    }
  }
```

Sample code to do POST operation
```
        session = redfish.redfish_client("https://xx.xx.xx.xx", "root", "mypassword", "/redfish/v1")
        session.login(auth=redfish.AuthMethod.SESSION)
        arg = { "ResetType": "GracefulShutdown" }
        response = session.post("/redfish/v1/Systems/1/Actions/ComputerSystem.Reset", args=arg)
        return response
```

What i get is this 
```
400

{
  "error": {
    "@Message.ExtendedInfo": [
      {
        "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
        "Message": "The request body submitted was malformed JSON and could not be parsed by the receiving service.",
        "MessageArgs": [],
        "MessageId": "Base.1.4.0.MalformedJSON",
        "Resolution": "Ensure that the request body is valid JSON and resubmit the request.",
        "Severity": "Critical"
      }
    ],
    "code": "Base.1.4.0.MalformedJSON",
    "message": "The request body submitted was malformed JSON and could not be parsed by the receiving service."
  }
}
```

Tried manually using request curl

```
$ curl -k -H "X-Auth-Token: N85b9ii31Ea9rjvjLnJH" -X POST https://${BMC_IP}/redfish/v1/Systems/1/Actions/ComputerSystem.Reset -d '{"ResetType": "GracefulShutdown"}'
{
  "@Message.ExtendedInfo": [
    {
      "@odata.type": "/redfish/v1/$metadata#Message.v1_0_0.Message",
      "Message": "Successfully Completed Request",
      "MessageArgs": [],
      "MessageId": "Base.1.4.0.Success",
      "Resolution": "None",
      "Severity": "OK"
    }
  ]
}
```
Works there..

**Comment by mraineri** [comment]
I believe you should be doing this instead:

```
        body = { "ResetType": "GracefulShutdown" }
        response = session.post("/redfish/v1/Systems/1/Actions/ComputerSystem.Reset", body=body)
```

At least on initial inspection I'm not entirely sure what "args" is for, but the "body" parameter is definitely the JSON payload for the request.

**Comment by mraineri** [comment]
Looking a bit more at args... It seems like for GET requests it'll add query parameters based on "args", but PUT, POST, and PATCH, it makes an odd format for the body and changes the Content-Type to "application/x-www-form-urlencoded". Very strange... I would like to clean that up, but in any case, you should be passing in your payload via the "body" parameter instead.

**Comment by gkeishin** [comment]
Sounds like a good plan there..  I key in the payload dictionary as part of the body and it work clean.  Thanks there..

**Comment by billdodd** [comment]
@mraineri - I agree; this code looks suspect: https://github.com/DMTF/python-redfish-library/blob/e4e2f583185b63ac385f68700f45a12f7499801a/src/redfish/rest/v1.py#L737-L739

But I'm not sure what it should really be doing. Need to investigate more.
