### ISSUE TITLE
pip package at pypi.org is wrong

### ISSUE THREAD

**Issue by jchia** [DMTF/python-redfish-library#28]
https://pypi.org/project/redfish/ shows that the current version is 2.0.6. However:

1. There is no 2.0.6 git tag.

1. More importantly, the pip content seems to be even older than the 2.0.5 git tag. For example, redfish_client takes a cafile argument in 2.0.5 but not in the pip package.

What git tag version does the '2.0.6' pip package correspond to? Was there a release error?

**Comment by mraineri** [comment]
The problem is I forgot to make the 2.0.6 tag in Github, even though all of the version numbers were updated and pushed to pip. I'll make a tag now.

**Comment by mraineri** [comment]
Tag (and release) for 2.0.6 created
