### ISSUE TITLE
Release on github and PyPI

### ISSUE THREAD

**Issue by stratakis** [DMTF/python-redfish-library#3]
Currently the project is not released on PyPI nor it has a tarball in github. Is it possible to create a tarball release?

**Comment by billdodd** [comment]
You can get the zip or tarball via these links:

https://github.com/DMTF/python-redfish-library/archive/master.zip
https://github.com/DMTF/python-redfish-library/archive/master.tar.gz

That said, providing the package on the PyPI site would be useful as well. Looking over the repo, the only issue I immediately see is that there is a package name conflict with an existing PyPI package. The top-level package defined here in `DMTF/python-redfish-library` is named `redfish`. And the following package on PyPI already provides a package named `redfish`:

https://pypi.python.org/pypi/python-redfish/0.4.1

**Comment by stratakis** [comment]
Hmm interesting. That poses the question if one of the upstreams should change its name. Definitely that would pose some conflicts in regards to downstream packaging (and not only).

**Comment by encukou** [comment]
Currently the README here says you can install this by `pip install python-redfish-library`. Since there's no release on PyPI, that doesn't work.

**Comment by mraineri** [comment]
Assigning to @jautor to work with the owner of the other tool

**Comment by seitzbg** [comment]
Any progress on being able to use pip?

**Comment by mraineri** [comment]
2/15: @jautor is currently working with the original tool's owner... Hopefully we'll get an answer shortly (and be able to publish it)...

**Comment by seitzbg** [comment]
Still not on PyPi and my work build system depends on being able to pull from there.  Is there an update on this?

TIA!

**Comment by mraineri** [comment]
3/15: @jautor is trying to get a response from the tool's owner; we'll think of alternatives in the meantime in case the owner is still unresponsive.

**Comment by seitzbg** [comment]
Any movement yet?

TIA,

**Comment by seitzbg** [comment]
Bump :)

**Comment by mraineri** [comment]
Discussion from 5/24: Will attempt to publish to PIP as is (despite the conflict not being able to be resolved). We cannot change the package name used since other communities are using this. We also still have not been successful about working with the other library's owner to fix the conflict. We will also update the readme to state that such a conflict exists, and a user can only have one package installed at a time.

**Comment by seitzbg** [comment]
Thank you for the followup.

**Comment by mraineri** [comment]
Took a while to resolve this... But you can get this with pip now (for both Python2 and Python3): `pip install redfish`

https://pypi.org/project/redfish/

**Comment by mraineri** [comment]
Closing; finally released...
