### ISSUE TITLE
KeyError: 'Links'

### ISSUE THREAD

**Issue by lichao0x7cc** [DMTF/python-redfish-library#4]
# Info
Huawei server
redfish v1

# Exception result
Traceback (most recent call last):
  File "/home/chao/PycharmProjects/texx/rfish.py", line 7, in <module>
    REDFISH_OBJ = redfish.redfish_client(base_url=login_host, username=login_account, password=login_password, default_prefix=default_prefix)
  File "/home/chao/Desktop/python-redfish-library/src/redfish/rest/v1.py", line 954, in redfish_client
    default_prefix=default_prefix, sessionkey=sessionkey)
  File "/home/chao/Desktop/python-redfish-library/src/redfish/rest/v1.py", line 894, in __init__
    self.login_url = self.root.Links.Sessions['@odata.id']
KeyError: 'Links'

# Description
login_host = https://x.x.x.x
i'm sure username and password correctly
default_prefix = /redfish/v1

**Comment by mraineri** [comment]
@lichao0x7cc can you please provide the JSON body of the Service Root resource? It looks like there is no "Links" object from what I can gather from the exception trace.

**Comment by mraineri** [comment]
Discussion 12/14: This appears to be an error on the service; the tool needs to log into the service, and in order to do so, it needs to find the Sessions collection link via the "Links" object in the service root.

**Comment by selund** [comment]
I've been in contact with Huawei, and they are now going to add Links in the next firmware release.

**Comment by lichao0x7cc** [comment]
> I've been in contact with Huawei, and they are now going to add Links in the next firmware release.

cool！

**Comment by lichao0x7cc** [comment]
Thanks

selund <notifications@github.com> 于2019年3月18日周一 下午4:49写道：
