### ISSUE TITLE
Unable to post body with boolen data

### ISSUE THREAD

**Issue by jixiang1912** [DMTF/python-redfish-library#43]
body = {"Enabled": true}
foo = redfish_client.patch('/redfish/v1/AccountService/Accounts/3', body=body)

Python will throw "NameError: name 'true' is not defined" error

How to set the body data in this case?

**Comment by mraineri** [comment]
When you set up the body like that, you're creating a python dictionary. It doesn't get converted until a call is made into the patch routine.

So, you need to set the body like this:
```
body = {"Enabled": True}
```

**Comment by 4383** [comment]
@jixiang1912 it's ok for you?
Do you need more help?

**Comment by mraineri** [comment]
6/20: Closing; problem with the Python syntanx in the submitter's code. Answer given for how to fix it.
