### ISSUE TITLE
Python 3.8.1 - AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by themichaelmitchell** [DMTF/python-redfish-library#75]
time.clock() appears to have been deprecated.

time.clock() is used [here](https://github.com/DMTF/python-redfish-library/blob/master/src/redfish/rest/v1.py#L814-L816)

replacing time.clock() with time.perf_counter() appears to solve this issue.

**Comment by mraineri** [comment]
Is perf_counter() available in older versions of Python?

**Comment by themichaelmitchell** [comment]
time.clock() appears to have been officially deprecated in 3.3, and removed in 3.7

https://bugs.python.org/issue31803

**Comment by mraineri** [comment]
Got it, thanks.

Will need to add Python version checks too since this library is expected to run in Python 2.7 too.
