### ISSUE TITLE
Remove old library dependency - urlparse2

### ISSUE THREAD

**Issue by mnhauke** [DMTF/python-redfish-library#78]
urlparse2 is an unmaintained library - last commit is 6 years old.
The library is not python3 compatible (at least it's dependecy - recordtype library).

HP's fork of python-redfish-library dropped urlparse2 last year...
https://github.com/HewlettPackard/python-ilorest-library/issues/28

Please, remove this dependency and use built-in functions to parse URL.
Thanks.

**Comment by jautor** [comment]
Thanks for calling this to our attention - we've updated the code to remove that dependency.
