### ISSUE TITLE
Socks proxy

### ISSUE THREAD

**Issue by neodino** [DMTF/python-redfish-library#8]
Any chance to implement proxy (SOCKS5) support?

**Comment by billdodd** [comment]
@neodino - you mention SOCKS5 proxy specifically. Does your use case really require a SOCKS5 proxy or would an http/https proxy suffice?

python-redfish-library uses the python http client (`httplib` in python 2, `http.client` in python 3). And it looks like the python http client has support for using http/https proxies. That could probably be leveraged by python-redfish-library.

References:
https://docs.python.org/2/library/httplib.html#httplib.HTTPConnection.set_tunnel
https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection.set_tunnel

**Comment by neodino** [comment]
Yes, using socks5. Creating socks proxy over ssh tunnel.
I did came across referenced but does not support socks5. Tried this:
https://stackoverflow.com/questions/44893913/how-can-you-connect-through-a-socks-proxy-with-python-httplib-http-client 
but now luck.
Any other idea?

**Comment by mraineri** [comment]
2/15: We'll have to think about this one more; we don't have a clear answer on how to do this either...

**Comment by mraineri** [comment]
6/7: @jautor will follow up with his team to see if this sort of functionality is reasonable

**Comment by mraineri** [comment]
But if you'd like to make changes to the library yourself, you're more than welcome to submit something!

**Comment by mraineri** [comment]
You're right; that should allow for SOCKS proxies now.

Would it be useful to add `requests[socks]` to requirements.txt?

**Comment by bb-Ricardo** [comment]
I would just add an additional comment to this section (https://github.com/DMTF/python-redfish-library#using-proxies) as I think it is a limited use case to require everyone to pull in an additional package.

**Comment by mraineri** [comment]
Great, thanks for the recommendation! I can update the readme for that
