### ISSUE TITLE
HTTP headers overwritten by library

### ISSUE THREAD

**Issue by andrzej-zamojski** [DMTF/python-redfish-library#92]
When using the library to verify proper Redfish service implementation behavior I encountered problem with sending a request with headers which value should not be accepted by the service.

It looks like requests with HTTP headers Accept or OData-Version are overwritten by the library, so I could not find a possibility to send for instance 'Accept': 'application/xml' header which should be rejected by the service, because it's overwritten in library with \*/\*. OData-Version 4.0 also cannot be replaced with a value which could be used to verify service implementation.

Is there any explanation for that ?
Is there any chance to change this behavior or make it somehow configurable?
Or maybe I'm doing something wrong ?
Code example below:

```
import redfish

REDFISH_OBJ = redfish.redfish_client(
        base_url='https://10.172.201.115',
        username='admin', password='admin',
        default_prefix='/redfish/v1')

REDFISH_OBJ.login()
iheaders = {'Accept': 'application/xml'}
response = REDFISH_OBJ.get('/redfish/v1/Managers', headers=iheaders)
print (response)
REDFISH_OBJ.logout()
```

**Comment by mraineri** [comment]
I can understand OData-Version being overwritten; anything other than "4.0" is outside scope of the Redfish spec and can result in undefined behavior.

Accept is a bit more problematic though; while the vast majority of Redfish will require "application/json", there are a handful of cases where that won't be the response (primarily $metadata as well as a few URIs that might result in application/octet-stream). I can understand overriding Accept in most cases though.

**Comment by andrzej-zamojski** [comment]
The problem is I can`t overwrite these values, so I cannot verify if a service reacts correctly on not expected headers values.
Do you have an idea how to continue?
Propose such change which would not overwrite these headers when are delivered by user?

**Comment by mraineri** [comment]
I think that sounds reasonable; only add the headers if not already specified by the user. Most users I would expect to never attempt to set these headers.

**Comment by andrzej-zamojski** [comment]
Hi, pull request for this topic is created (https://github.com/DMTF/python-redfish-library/pull/94).

**Comment by mraineri** [comment]
PR merged
